/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

import DAO.PessoaFisicaDAO;
import DAO.PessoaJuridicaDAO;
import DTO.PessoaFisicaDTO;
import DTO.PessoaJuridicaDTO;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;


/**
 *
 * @author thiag
 */
public class PerfilVIEW extends javax.swing.JInternalFrame {

    /**
     * Creates new form PerfilVIEW
     */
    public PerfilVIEW() {
        initComponents();
       
            
    }
    
    public void listarValores(){
        try {
            // Cria uma instancia da classe PessoaFisicaDAO
            PessoaFisicaDAO objdao = new PessoaFisicaDAO();
            
            /*
            Chama o método BuscarPorCpf para buscar os dados da
            tabela pessoa_fisica no banco de dados
            */
            PessoaFisicaDTO objdto = objdao.BuscarPorCpf();
            
            // Preenche os campos txt com os dados obtidos
            txtNome.setText(objdto.getNome() + " " + objdto.getSobrenome());
            txtCpf.setText(objdto.getCpf());
            
            /*
            Recebendo o numero da conta da pessoa fisica e
            convertendo para String
            */
            String conta = objdto.getConta();
            String contaString = String.valueOf(conta);
            /*
            Recebendo o numero da agencia da pessoa fisica e 
            convertendo para String
            */
            String agencia = objdto.getAgencia();
            String agenciaString = String.valueOf(agencia);
           
            //Preenchendo os campos com os dados obtidos pela váriavel convertida.
            txtConta.setText(contaString);
            txtAgencia.setText(agenciaString);
            System.out.println("Conta: " + conta + "\nAgencia: " + agencia);
        // Caso de algum erro dentro do método, aparecerá este erro
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Listar erro "
                    + e);
            
        } 
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtAgencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setRequestFocusEnabled(false);
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome completo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 97, -1, -1));

        txtNome.setEditable(false);
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 134, 164, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cpf:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 171, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Agência:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 372, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Conta:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 372, -1, -1));

        txtConta.setEditable(false);
        jPanel1.add(txtConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 376, 164, -1));

        txtCpf.setEditable(false);
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 208, 164, -1));

        txtAgencia.setEditable(false);
        jPanel1.add(txtAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 376, 139, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pfp.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 71, 208, 208));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Logotipo_de_Finanças_e_Banco_Moderno_Gradiente_Preto_e_Dourado-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtConta;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
