package VIEW;
import DAO.PessoaFisicaDAO;
import DAO.PessoaJuridicaDAO;
import DTO.PessoaFisicaDTO;
import DTO.PessoaJuridicaDTO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;import javax.swing.JCheckBox;

public class TelaLoginVIEW extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginVIEW
     */
    public TelaLoginVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCampoSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtCampoTexto = new javax.swing.JTextField();
        CheckBox = new javax.swing.JCheckBox();
        botaoAcessar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botaoCriarConta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Acesse sua conta");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 290, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CPF/CPNJ:");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        txtCampoSenha.setBackground(new java.awt.Color(204, 255, 204));
        txtCampoSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCampoSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCampoSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCampoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCampoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 260, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SENHA:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        txtCampoTexto.setBackground(new java.awt.Color(204, 255, 204));
        txtCampoTexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCampoTexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCampoTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCampoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoTextoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCampoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 260, 20));

        CheckBox.setBackground(new java.awt.Color(204, 204, 204));
        CheckBox.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CheckBox.setForeground(new java.awt.Color(0, 0, 0));
        CheckBox.setText("Mostrar a Senha");
        CheckBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CheckBox.setOpaque(false);
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 20));

        botaoAcessar.setBackground(new java.awt.Color(204, 255, 204));
        botaoAcessar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoAcessar.setForeground(new java.awt.Color(0, 0, 0));
        botaoAcessar.setText("Acessar");
        botaoAcessar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoAcessar.setFocusPainted(false);
        botaoAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcessarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 260, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Não tem conta?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        botaoCriarConta.setBackground(new java.awt.Color(204, 255, 204));
        botaoCriarConta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoCriarConta.setForeground(new java.awt.Color(0, 0, 0));
        botaoCriarConta.setText("Crie sua conta");
        botaoCriarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoCriarConta.setFocusPainted(false);
        botaoCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarContaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCriarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 400, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Todos os direitos reservados");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("X");
        jButton1.setAlignmentY(0.0F);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false
        );
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 0, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Logotipo_de_Finanças_e_Banco_Moderno_Gradiente_Preto_e_Dourado-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarContaActionPerformed
        DescisaoVIEW ds = new DescisaoVIEW();
        ds.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCriarContaActionPerformed

    private void botaoAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcessarActionPerformed
        try{
            String cpf, Senha;
            String cnpj, senha;
            /*
            Recebe os valores digitados nos campos de texto
            para Cpf e Senha da Pessoa Fisica, Cnpj e Senha
            da Pessoa Juridica
            */
            cpf = txtCampoTexto.getText();
            Senha = txtCampoSenha.getText();
            cnpj = txtCampoTexto.getText();
            senha = txtCampoSenha.getText();

            // Instanciando a classe PessoaFisicaDTO
            PessoaFisicaDTO cfdto = new PessoaFisicaDTO();
            /* O valor que está na váriavel cpf o sistema
            irá comparar com o que está no banco de dados,
            tanto o Cpf tanto a Senha
            */
            cfdto.setCpf(cpf);
            cfdto.setSenha(Senha);

            // Instanciando a classe PessoaFisicaDAO
            PessoaFisicaDAO cfdao =  new PessoaFisicaDAO();

            /* Usando o ResultSet assim ele consegue fazer a autenticação,
            e assim verificando se o cpf e a senha informados são os
            mesmo do banco de dados na tabela pessoa fisica
            */
            ResultSet rscfdao = cfdao.autenticacaoUsuario(cfdto);

            // Instanciando a classe PessoaJuridicaDTO
            PessoaJuridicaDTO cjdto = new PessoaJuridicaDTO();
            /*
            O valor que está na váriavel cnpj, o sistema irá
            comparar com o que está no banco de dados, tanto
            o Cnpj tando a Senha
            */
            cjdto.setCnpj(cnpj);
            cjdto.setSenha(senha);

            // Instanciando a classe PessoaJuridicaDAO
            PessoaJuridicaDAO cjdao = new PessoaJuridicaDAO();

            /* Usando o ResultSet assim ele consegue fazer a autenticação,
            e assim verificando se o cnpj e a senha informados são os
            mesmo do banco de dados na tabela pessoa juridica
            */
            ResultSet rscjdao =  cjdao.autenticacaoJuridica(cjdto);

            /*
            Verifica se a autenticação foi bem-sucedida para pessoa
            fisica ou juridica
            */
            if (rscfdao.next() || rscjdao.next()){
                TelaPrincipalVIEW telaPrincipal = new TelaPrincipalVIEW();
                telaPrincipal.setVisible(true);
                dispose(); // fecha a tela login
            }

            /*
            Cai aqui caso o cpf/cpnj e senha forem informados errados ou
            se caso não tiverem registrados
            */
            else{
                // enviar mensagem dizendo incorreto.
                JOptionPane.showMessageDialog(null, "Cpf e/ou Senha incorreto(s)!");
            }

            // Cai aqui se caso a conexão não for bem-sucedida
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "TelaLoginVIEW" + e);
        }
    }//GEN-LAST:event_botaoAcessarActionPerformed

    private void CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxActionPerformed

        if (CheckBox.isSelected()){
            /* se caso a caixa de seleção "mostrarSenha" estiver marcada
            exibe a senha em texto no campo password
            */
            txtCampoSenha.setEchoChar((char)0); // Exibe a Senha
            CheckBox.setText("Esconder senha");
        } else {
            /*
            // Caso contrário, oculta a senha com asteriscos
            (o comportamento padrão)
            */
            txtCampoSenha.setEchoChar('*'); // Oculta a senha com asteriscos
            CheckBox.setText("Mostrar senha");
        }
    }//GEN-LAST:event_CheckBoxActionPerformed

    private void txtCampoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoTextoActionPerformed

    private void txtCampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoSenhaActionPerformed

    }//GEN-LAST:event_txtCampoSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    private void gravaInfo(){
        PessoaFisicaDTO objCfdto = new PessoaFisicaDTO();
        PessoaJuridicaDTO objCjdto = new PessoaJuridicaDTO();
        String txtCampo = txtCampoTexto.getText();
        objCfdto.setCpf(txtCampo);
        objCjdto.setCnpj(txtCampo);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox;
    private javax.swing.JButton botaoAcessar;
    private javax.swing.JButton botaoCriarConta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPasswordField txtCampoSenha;
    private javax.swing.JTextField txtCampoTexto;
    // End of variables declaration//GEN-END:variables
}
